### ISSUE TITLE
Multi-platform docker images pushed to DockerHub

### ISSUE THREAD

**Issue by docktermj** [Senzing/senzingapi-runtime#59]

**Comment by docktermj** [comment]
Spike at https://github.com/Senzing/test-ground/issues/143

**Comment by docktermj** [comment]
Prototype of `.github/workflows/build-docker-containers.yaml`

```yaml
name: build-docker-containers.yaml
on:
  push:
    branches:
      - 143.dockter.1
  workflow_dispatch:
jobs:
  build-docker-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: git config
        run: |
          git config user.name github-actions
          git config user.email support@senzing.com
      - name: Print environment variables
        run: printenv
      - name: Git Merge With Main
        run: git merge origin/main
      - name: Git Update submodules
        run: git submodule update --init --recursive
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker list platforms
        run: docker buildx ls
      - name: Dockerhub login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      - name: Docker image build
        run: |
          docker buildx build \
            --push \
            --platform linux/arm64,linux/amd64 \
            --build-arg SENZING_APT_INSTALL_PACKAGE=senzingapi-runtime \
            --build-arg SENZING_APT_REPOSITORY_NAME=senzingstagingrepo_1.0.1-1_all.deb \
            --build-arg SENZING_APT_REPOSITORY_URL=https://senzing-staging-apt.s3.amazonaws.com \
            --build-arg SENZING_APT_INSTALL_PACKAGE=senzingapi-runtime=3.8.0-23258 \
            --no-cache \
            --tag senzing/test-ground:1.1.1 \
            .
```
